spring:
  liquibase:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  r2dbc:
    url: r2dbc:postgresql://localhost:5434/user_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    liquibase: DEBUG

minio:
  url: http://localhost:9000
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  bucket: ${BUCKET}

internal:
  jwt:
    secret: "12345678901234567890123456789012" # ровно 32 символа

#gateway:
#  public-paths:
#    - /v3/api-docs/**
#    - /swagger-ui/**
#    - /swagger-ui.html
#    - /actuator/**

