spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/user_db
    username: user
    password: password

yandex:
  geocoder:
    key-file: config/yandex/authorized_key.json
    api-key: 703e6b5f-acd1-4aa8-b4f0-051633057e0e

server:
  port: 7070