package com.simple.taxi.dto;

public enum NotificationType {
    REGISTRATION_CONFIRMATION,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    LOGIN_ALERT,
    RESEND_CONFIRMATION,
    TWO_FACTOR_AUTHENTICATION_CONFIRMATION,
}