services:
  user_postgres:
    image: postgres:17
    container_name: user_postgres
    restart: on-failure
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"